package com.limbo.Pages;

import com.limbo.entities.Producte;
import com.limbo.service.ProducteServiceAccess;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author RaulM
 */
public class TaulaProductes extends javax.swing.JPanel {
    ProducteServiceAccess psa = new ProducteServiceAccess();

    /**
     * Creates new form TaulaProductes
     */
    public TaulaProductes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();


        String[] col = {"Número de producte", "Nom de Producte", "Descripcio", "PVP", "IVA", "Marca", "Unitat de Mesura", "Pes", "Categoria"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);

        try {
            Vector<Producte> productes = psa.taulellProductes();

            for (Producte producte : productes) {
                int idProducte = producte.getId();
                String nom = producte.getNom();
                String descripcio = producte.getDescripcio();
                double pvp = producte.getPvp();
                int iva = producte.getIva();
                String marca = producte.getMarca();
                String unitat_mesura = producte.getUnitat_mesura();
                double pes = producte.getPes();
                String cat = producte.getCategoria();

                Object[] obj = {
                        idProducte, nom, descripcio, pvp, iva, marca, unitat_mesura, pes, cat
                };

                tableModel.addRow(obj);

            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de productes", JOptionPane.ERROR_MESSAGE);
        }

        jTable1 = new JTable(tableModel);

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(450, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(174, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}
